### ISSUE TITLE
Response times have increased

### ISSUE THREAD

**Issue by SwixDevs** [DashCruft/discord.js-custom-prefix#2]
So once I implemented this, it's all working perfectly fine, but I have one big problem.
The response times have increased by A LOT.

Probably because of this line- (The await)
`const data = await prefix.findOne({
        GuildID: message.guild.id
    });`

Is there any way to make it faster?

**Comment by p0ryae** [comment]
Hey SwixDevs!

Interesting... Maybe the MongoDB region is in bad position of your host? The bot's speed cannot be controlled by the code. It depends on the database and the host condition! 

Regards,
DashCruft

**Comment by SwixDevs** [comment]
The main problem is that the prefix is fetched according to the guild ID in EVERY single message event, and it is not stored in cache.
Thus, it takes a lot of time to fetch it, and then to run the actual command.
How would I go about saving it in app cache?

**Comment by p0ryae** [comment]
Well thats the way it should work.

**Comment by SwixDevs** [comment]
It's not very performant. A better way to do it would be storing the prefix of each guild in the database, as well as the bot's cache.

So, if the prefix is not in the cache when a command is used, it would be fetched from the database, and after that, whenever someone uses a command in that server, it gets fetched from the cache, which is faster than doing the same thing with the database.

**Comment by SwixDevs** [comment]
Response time will be the same if we do not save the the prefix in the bot's cache as well as the database.
